import { OverallIndScore } from '../../../interface';

export const leaderboard: OverallIndScore[] = [
  {
    name: 'Brooks DuBose',
    thursdayScore: 2,
    fridayScore: 39,
    saturdayScore: 63,
    sundayScore: 21,
    overallScore: 125,
  },
  {
    name: 'Jody Lyles',
    thursdayScore: 35,
    fridayScore: 56,
    saturdayScore: 30,
    sundayScore: 9,
    overallScore: 130,
  },
  {
    name: 'Scott Strickland',
    thursdayScore: 28,
    fridayScore: 17,
    saturdayScore: 58,
    sundayScore: 0,
    overallScore: 103,
  },
  {
    name: 'Rawls Zollicoffer',
    thursdayScore: 33,
    fridayScore: 25,
    saturdayScore: 49,
    sundayScore: -6,
    overallScore: 101,
  },
  {
    name: 'Walt Reece',
    thursdayScore: 9,
    fridayScore: 54,
    saturdayScore: 46,
    sundayScore: 0,
    overallScore: 109,
  },
  {
    name: 'Mark Karavan',
    thursdayScore: 35,
    fridayScore: 49,
    saturdayScore: 29,
    sundayScore: 3,
    overallScore: 116,
  },

  {
    name: 'Woody Houck',
    thursdayScore: 21,
    fridayScore: 38,
    saturdayScore: 34,
    sundayScore: 31,
    overallScore: 124,
  },
  {
    name: 'Chase Bussell',
    thursdayScore: 17,
    fridayScore: 51,
    saturdayScore: 61,
    sundayScore: -3,
    overallScore: 126,
  },
  {
    name: 'Seth Maness',
    thursdayScore: 38,
    fridayScore: 34,
    saturdayScore: 38,
    sundayScore: 14,
    overallScore: 124,
  },
];
